# Generated by Django 3.1 on 2020-10-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHealthCareUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.healthcareuser',),
        ),
        migrations.CreateModel(
            name='DoctorHealthCareUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.healthcareuser',),
        ),
        migrations.CreateModel(
            name='ImagingHealthCareUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.healthcareuser',),
        ),
        migrations.CreateModel(
            name='LaboratoryHealthCareUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.healthcareuser',),
        ),
        migrations.CreateModel(
            name='NurseHealthCareUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.healthcareuser',),
        ),
    ]
